version: '3'

services:
  postgres:
    image: postgres:10
    hostname: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: playground
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

  adminer:
    image: adminer
    hostname: adminer
    container_name: adminer
    ports:
      - 9080:8080
    depends_on:
      - postgres
